{% set version = "110" %}

package:
  name: binaryen
  version: {{ version }}

source:
  url: https://github.com/WebAssembly/binaryen/archive/version_{{ version }}.tar.gz
  sha256: 0f80250a02b94dd81bdedeae029eb805abf607fcdadcfee5ca8b5e6b77035601
  patches:
    # this fixes an issue where "some toolchains it is necessary to #define __STDC_FORMAT_MACROS before using macros like PRIxPTR"
    # cf: https://github.com/tensorflow/tensorflow/issues/12998#issuecomment-329179887
    - gcc_stdmacro.patch  # [linux]

build:
  number: 0

requirements:
  build:
    - {{ compiler("c") }}
    - {{ compiler("cxx") }}
    - cmake
    - ninja

test:
  commands:
    - wasm-shell --help
    - wasm-opt --help
    - wasm-metadce --help
    - wasm2js --help
    - wasm-emscripten-finalize --help
    - wasm-as --help
    - wasm-dis --help
    - wasm-ctor-eval --help
    - wasm-reduce --help

about:
  home: https://github.com/WebAssembly/binaryen
  license: Apache-2.0
  license_file: LICENSE
  summary: Compiler infrastructure and toolchain library for WebAssembly, in C++

extra:
  recipe-maintainers:
    - jakirkham
    - wolfv
    - martinRenou
