travis:
  secure:
    BINSTAR_TOKEN: XgBc4RtmNKvRWsjlnpR31otx+IFITPseXNIv2nUV4y4oWskcp8UZ4IPBad5fYXVhmIQut7+JJfmEyKR09r2PH33PuZkBg5CO8thXjCqDUn/pRI6FpBBGR5Cu5VG/pZKn04TyhyzJRkOeutFqj6Qcob9sMRw4dFwr7L9S9iP5pqMAbjGU+dLptf3pny3vMKLYItAYW8AkOztdA726///G8cI+PRVaT3bxNmuNXmckZ6rq35l8rU9AEPW6xGQXeQxPz8tWP2Ua7N36TECIFgfecCimuh56gbjDpcSPw0IH9+XCs/t4Z/m5FVLnJxcRjYAa8uR7EDfaq4bt0+NoOS/UaBQ+Jyg7p2yELJCnwYv1fHnz16rgze4km9xnOa+RiXbTfb1ulYMPhHBRIs1w1w8suJpBzGhtXdKcLTqYjrCadZA0yyFACw3XJW2anuWP8dl+vcwThVYqsAoZnoaFEFKrtOGZP5gitfDSkLl+jQXPbhHOLy91UxbGsh9ckKi19+DEc2ydcfMvwB1X3J2q17VJ1IhJNSGcEaot3O4U9Vde8jp38xrT2ejch18G8jI8TZK8aG6BLE8CnoQlq0TSpxs/hOtMlFe+Z0YRkqq1mEr5Gbkw1naJ8EI01njE0cFrkNW5sBpLcdBuHuvo4rKdgubTSR7x7TLDCAKPRKTrck2IjN0=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
